language: java
jdk:
  - openjdk17

branches:
  only:
    - main
    - develop

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true

script:
  - mvn test

cache:
  directories:
    - ~/.m2
